<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Briderk" failures="1" tests="2" name="MyTest" time="0.084" errors="0" timestamp="2023-10-31T18:32:13 IST">
  <testcase classname="appid.test" name="logtest1" time="0.017"/>
  <testcase classname="appid.test" name="logtest2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
at appid.test.logtest2(test.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- logtest2 -->
</testsuite> <!-- MyTest -->
